import './globals.css'
import type { Metadata } from 'next'
import { Bai_Jamjuree as Bai, Roboto_Flex as Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' });
const bai = Bai({ subsets: ['latin'], weight: '700', variable:'--font-bai' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${bai.variable} font-sans`}>{children}</body>
    </html>
  )
}
